apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: electronix

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      nodeSelector:
         workload: application

      containers:
      - name: mysql

        image: mysql:8.0.41

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: electronix-config
              key: DB_NAME

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: electronix-secret
              key: DB_PASSWORD

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc